### PR TITLE
Add support for exporting to duckdb (via parquet)

### PR DESCRIPTION
**Pull request by mwip**
This patch adds functionality to export directly to a DuckDB database via the --duckdb flag or using a ".duckdb" or ".db" file. Optionally one can change the table name in which data will be imported.

Documentation was mostly copied from existing functions but doctests were updated and checked for consistency with the results.

Closes kraina-ai/quackosm#94

### CODE REVIEW

**Comment by mwip** [comment]
As some of the runners fail and I am not too familiar with your CD requirements, @RaczeQ, maybe you can give me some hints on what to address first? This is not to pressure, rather I thought I'd ask how I can be most helpful with regards to your workflows. Just let me know

**Comment by RaczeQ** [comment]
Hi @mwip, sorry for the late reply.

From what I can see, the tests aren't working and there are some `refurb` suggestions to keep good coding conventions.
Here are the suggestions to apply:
image

If you want to run tests locally, there are two commands you can use:
- doctests: `pytest -v -s --durations=20 --doctest-modules --doctest-continue-on-failure quackosm`
- normal tests: `pytest -v -s --durations=20 tests/base`

I have to admit that I didn't prepare any instructions for collaborating, so sorry for that 😅

**Comment by mwip** [comment]
@RaczeQ awesome. Thanks for the hints. This will help me figuring it out. I'll work on this this weekend.

I just thought this might be a good indication to create a  "Contributing" section. Only if you're expecting many community contributions, of course. If you think this warrants the effort, I'd be happy to help with that. As I don't want to force you as the maintainer, feel free to open a dedicated issue and tag me.

**Comment by mwip** [comment]
I think this should've fixed all issues introduced by me.

**Pull request merged**
